create database PetHappy
GO
CREATE TABLE CLIENTE(
IDCLI INT IDENTITY (1,1),
NOMCLI VARCHAR (60),
APECLI VARCHAR (60),
DICCLI VARCHAR (60),
TELCLI CHAR(9),
DNICLI CHAR(8),
CODUBI CHAR(6),
CONSTRAINT IDCLI_PK PRIMARY KEY (IDCLI),
)
GO

CREATE TABLE VENDEDOR(
IDVEN INT ,
NOMVEN VARCHAR (60),
APEVEN VARCHAR (60),
DICVEN VARCHAR (60),
TELVEN CHAR(9),
DNIVEN CHAR(8),
CODUBI CHAR(6),
CONSTRAINT IDVEN_PK PRIMARY KEY (IDVEN),
)
GO
CREATE TABLE UBIGEO(
CODUBI CHAR(6),
DEPUBI VARCHAR(60),
PROVUBI VARCHAR(60),
DISTUBI VARCHAR(60),
CONSTRAINT CODUBI_PK PRIMARY KEY (CODUBI),
)
GO
CREATE TABLE PRODUCTO(
CODPRO INT,
NOMPRO VARCHAR (60),
MARPRO VARCHAR (60),
PREPRO INT,
CATPRO VARCHAR (60),
CONSTRAINT CODPRO_PK PRIMARY KEY (CODPRO),
)
GO
CREATE TABLE VENTA (
IDVENT INT IDENTITY (1,1),
FECVEN DATE DEFAULT GETDATE(),
ESTVENT  CHAR(1) DEFAULT 'A',
IDCLI INT,
IDVEN INT,
CODPRO INT,
CONSTRAINT IDVENT_PK PRIMARY KEY (IDVENT),
)
GO
CREATE TABLE VENTA_DETALLE(
IDVENTDET INT IDENTITY (1,1),
IDEVENT INT,
CODPRO INT,
CONSTRAINT IDVENTDET_PK PRIMARY KEY (IDVENTDET),
)
GO

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_UBIGEO
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);
GO
ALTER TABLE VENDEDOR ADD CONSTRAINT VENDEDOR_UBIGEO
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);
GO
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);
GO

ALTER TABLE VENTA ADD CONSTRAINT VENTA_VENTA_DETALLE
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPRO);
GO
